In [1]:
import numpy as np

1. Arrays, size, shape
1. Estadística de arreglos
1. Slicing y fancy indexing
1. Creación de mallas

# Numpy
Numpy (Numerical Python) se describe como la paquetería fundamental para el cómputo científico en Python. Ademas de ofrecer diversas herramientas para el cálculo numérico, numpy se especializa en arreglo de n-dimensiones.

## 1. Un nuevo objeto
El elemento básico de Numpy es el _array_.

In [2]:
lista = [1,2,3,4,5]
type(lista)

list

In [3]:
arr = np.array([1,2,3,4])
type(arr)

numpy.ndarray

### 1.1  Atributos básicos del array
- shape: una tupla que contiene el número de elementos (o longitud) para cada dimensión (axis) del array
- size: el número total de elementos en el array
- ndim: el número de dimensiones (axes)

In [4]:
arr = np.array([[1,2,3],
                [4,5,6]])

In [5]:
arr.shape

(2, 3)

In [6]:
arr.size

6

In [7]:
arr.ndim

2

Una característica del array es que la forma debe ser "rectangular", es decir, cada fila debe tener el mísmo número de columnas

In [8]:
arr = np.array([[1,2,3],
                [4,5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 2. Formas de crear arrays
Podemos convertir elementos como listas o tuplas a arrays o utilizar las funciones de numpy para crearlas

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

Para crear arreglos con un incremento dado utilizamos **np.arange()**

In [14]:
np.arange(4)

array([0, 1, 2, 3])

In [15]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(4,12,2)

array([ 4,  6,  8, 10])

In [17]:
np.arange(4,12,0.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4,
       10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8])

Para crear arreglos con un número específico de elementos utilizamos **np.linspace()**. Por default el número de elementos son 50

In [18]:
np.linspace(10)

TypeError: linspace() missing 1 required positional argument: 'stop'

In [19]:
np.linspace(3,10)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [20]:
np.linspace(3,10).shape

(50,)

In [21]:
np.linspace(4,10,3)

array([ 4.,  7., 10.])

In [22]:
np.linspace(4,100,150)

array([  4.        ,   4.6442953 ,   5.2885906 ,   5.93288591,
         6.57718121,   7.22147651,   7.86577181,   8.51006711,
         9.15436242,   9.79865772,  10.44295302,  11.08724832,
        11.73154362,  12.37583893,  13.02013423,  13.66442953,
        14.30872483,  14.95302013,  15.59731544,  16.24161074,
        16.88590604,  17.53020134,  18.17449664,  18.81879195,
        19.46308725,  20.10738255,  20.75167785,  21.39597315,
        22.04026846,  22.68456376,  23.32885906,  23.97315436,
        24.61744966,  25.26174497,  25.90604027,  26.55033557,
        27.19463087,  27.83892617,  28.48322148,  29.12751678,
        29.77181208,  30.41610738,  31.06040268,  31.70469799,
        32.34899329,  32.99328859,  33.63758389,  34.28187919,
        34.9261745 ,  35.5704698 ,  36.2147651 ,  36.8590604 ,
        37.5033557 ,  38.14765101,  38.79194631,  39.43624161,
        40.08053691,  40.72483221,  41.36912752,  42.01342282,
        42.65771812,  43.30201342,  43.94630872,  44.59

¿Cómo crear matrices de diferentes tamaño?

In [28]:
arr = np.arange(1,21)

In [29]:
arr.shape

(20,)

In [31]:
arr.reshape(4,5)

In [34]:
arr.reshape(2,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [35]:
np.arange(20).reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

### 3. Indexing y slicing

In [37]:
arr_1d = np.arange(0,101,10)
arr_1d

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [38]:
arr_1d[3]

30

In [39]:
arr_1d[-1]

100

In [40]:
arr_1d[-3]

80

In [41]:
arr_1d[:5]

array([ 0, 10, 20, 30, 40])

In [42]:
arr_1d[2:5]

array([20, 30, 40])

In [44]:
arr_1d[0:10:2]

array([ 0, 20, 40, 60, 80])

In [45]:
arr_1d[::2]

array([  0,  20,  40,  60,  80, 100])

In [46]:
arr_1d[::-2]

array([100,  80,  60,  40,  20,   0])

In [48]:
arr_1d[-4:-1:-1]

array([], dtype=int32)

In [50]:
arr_2d = np.arange(12).reshape(3, 4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
arr_2d.shape

(3, 4)

In [56]:
arr_2d[0][2]

2

In [57]:
arr_2d[0, 2]

2

In [60]:
arr_2d[0,:]

array([0, 1, 2, 3])

In [61]:
arr_2d[:,2]

array([ 2,  6, 10])

In [62]:
arr_2d[:2,:3]

array([[0, 1, 2],
       [4, 5, 6]])

### 4. Operaciones con arrays

In [68]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]

In [69]:
list(map(lambda x, y: x+y,list1, list2))

[6, 8, 10, 12]

In [70]:
arr1 = np.array(list1)
arr2 = np.array(list2)

In [71]:
arr1 + arr2

array([ 6,  8, 10, 12])

In [72]:
arr3 = np.array([9,10,11,12,13])

In [74]:
arr1+arr3

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [75]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

In [76]:
mat1+mat2

array([[ 6,  8],
       [10, 12]])

In [77]:
arr1-arr2

array([-4, -4, -4, -4])

In [78]:
arr1*arr2

array([ 5, 12, 21, 32])

In [79]:
arr1/arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [81]:
arr1+10

array([11, 12, 13, 14])

In [82]:
arr1/10

array([0.1, 0.2, 0.3, 0.4])