In [1]:
import numpy as np

# Numpy
Numpy (Numerical Python) se describe como la paquetería fundamental para el cómputo científico en Python. Además de ofrecer diversas para el cálculo númericos, numpy se especializa en arreglos de n-dimensiones.

## 1. Un nuevo objeto
El elemento básico de Numpy es el array

In [2]:
lista = [1,2,3,4]
type(lista)

list

In [3]:
arr = np.array([1,2,3,4])
type(arr)

numpy.ndarray

1.1 Atributos básicos del array
- shape: una tupla que contiene el número de elementos (o longitud) para cada dimensión (axis) del array
- size: el número total de elementos en el array
- ndim: el número de dimensiones (axes)

In [7]:
arr = np.array([[1,2,3], [4,5,6]])

In [8]:
arr.shape

(2, 3)

In [9]:
arr.size

6

In [10]:
arr.ndim

2

Una característica del array es que la forma debe ser "rectangular", es decir, cada fila debe tener el mismo número de columnas

In [12]:
np.array([[1,2,3],[4,5, np.nan]])

array([[ 1.,  2.,  3.],
       [ 4.,  5., nan]])

In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
arr.shape

(3, 3)

### 2. Formas de crear arrays

In [17]:
np.zeros(2)

array([0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
arr_0 = np.zeros((2,3,4))

In [21]:
arr_0.ndim

3

In [22]:
arr_0.size

24

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

Para crear arreglos con un incremento dado **np.arange()**

In [25]:
np.arange(4)

array([0, 1, 2, 3])

In [26]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

In [31]:
np.arange(3,12,0.2)

array([ 3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,
        5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,
        7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,
        9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6,
       11.8])

Para crear arreglos con un número específico de elementos, utilizamos **np.linspace()**. 

In [34]:
np.linspace(3,10).size

50

In [35]:
np.linspace(3,10,3)

array([ 3. ,  6.5, 10. ])

In [36]:
np.linspace(4,100,150)

array([  4.        ,   4.6442953 ,   5.2885906 ,   5.93288591,
         6.57718121,   7.22147651,   7.86577181,   8.51006711,
         9.15436242,   9.79865772,  10.44295302,  11.08724832,
        11.73154362,  12.37583893,  13.02013423,  13.66442953,
        14.30872483,  14.95302013,  15.59731544,  16.24161074,
        16.88590604,  17.53020134,  18.17449664,  18.81879195,
        19.46308725,  20.10738255,  20.75167785,  21.39597315,
        22.04026846,  22.68456376,  23.32885906,  23.97315436,
        24.61744966,  25.26174497,  25.90604027,  26.55033557,
        27.19463087,  27.83892617,  28.48322148,  29.12751678,
        29.77181208,  30.41610738,  31.06040268,  31.70469799,
        32.34899329,  32.99328859,  33.63758389,  34.28187919,
        34.9261745 ,  35.5704698 ,  36.2147651 ,  36.8590604 ,
        37.5033557 ,  38.14765101,  38.79194631,  39.43624161,
        40.08053691,  40.72483221,  41.36912752,  42.01342282,
        42.65771812,  43.30201342,  43.94630872,  44.59

¿Cómo crear matrices de diferentes dimensiones?

In [37]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
arr.reshape(4,6)

ValueError: cannot reshape array of size 20 into shape (4,6)

In [39]:
arr.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [40]:
arr.reshape(2,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [42]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### 3. Indexing y slicing

In [44]:
arr_1d = np.arange(0,101,10)
arr_1d

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [45]:
arr_1d[3]

30

In [47]:
arr_1d[10]

100

In [48]:
arr_1d[-1]

100

In [49]:
arr_1d[-3]

80

In [50]:
arr_1d

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [51]:
arr_1d[:5]

array([ 0, 10, 20, 30, 40])

In [52]:
arr_1d[2:5]

array([20, 30, 40])

In [54]:
arr_1d[0:11:2]

array([  0,  20,  40,  60,  80, 100])

In [53]:
arr_1d[::2]

array([  0,  20,  40,  60,  80, 100])

In [57]:
arr_1d[-1:0:-2]

array([100,  80,  60,  40,  20])

In [61]:
arr_1d[-1::-2]

array([100,  80,  60,  40,  20,   0])

In [58]:
arr_1d[::-2]

array([100,  80,  60,  40,  20,   0])

In [69]:
np.arange(0,12).reshape(3,2,-1) # -1 calcula el número elemento faltante

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [70]:
np.arange(0,12).reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
arr_2d = np.arange(0,12).reshape(3,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
arr_2d[0,3]

3

In [78]:
arr_2d[1,:]

array([4, 5, 6, 7])

In [79]:
arr_2d[:,2]

array([ 2,  6, 10])

In [82]:
arr_2d[:2,:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [83]:
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
arr_2d[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

### 4. Operaciones con arrays

In [88]:
list1 = [1,2,3,4]
list2 = [4,5,6,7]

In [89]:
list1+list2

[1, 2, 3, 4, 4, 5, 6, 7]

In [91]:
list(map(lambda x, y: x+y, list1,list2))

[5, 7, 9, 11]

In [93]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,5,6,7])

In [94]:
arr1+arr2

array([ 5,  7,  9, 11])

In [96]:
np.concatenate([arr1,arr2])

array([1, 2, 3, 4, 4, 5, 6, 7])

In [97]:
arr3 = np.array([8,9,10,11,12])

In [98]:
arr1+arr3

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [99]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

In [100]:
mat1+mat2

array([[ 6,  8],
       [10, 12]])

In [103]:
arr1@arr2

60

In [102]:
arr1/arr2

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [104]:
arr1/10

array([0.1, 0.2, 0.3, 0.4])

In [107]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [108]:
mat1@mat2

array([[19, 22],
       [43, 50]])

In [109]:
mat1*mat2

array([[ 5, 12],
       [21, 32]])